name: Docker Image CI
on:
  workflow_dispatch:

jobs:
  mvn:

    runs-on: ubuntu-latest
    environment:
      name: test
      url: test.ts
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: up
      run: java -jar target/*.jar
  
  
