name: Docker Image CI
on:
  workflow_dispatch:

jobs:
  mvn:

    runs-on: ubuntu-latest
    environment:
      name: test
      url: test.ts
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6


  docker:

    runs-on: ubuntu-latest
    environment:
      name: test
      url: test.ts
    needs: mvn
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up
  
